// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_IMAGEVIEW_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the resource URL of the image to display. \
  * \
  * The image is loaded asynchronously. Use ResourceReadySignal() to be \
  * notified when loading completes. \
  * \
  * @param[in] url The URL of the image resource \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetResourceUrl(const Dali::String& url) { ImageView::SetResourceUrl(url); return *this; } \
  /** \
  * @brief Sets the URL of a placeholder image shown while the main image is loading. \
  * \
  * @param[in] url The URL of the placeholder image resource \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPlaceholderUrl(const Dali::String& url) { ImageView::SetPlaceholderUrl(url); return *this; } \
  /** \
  * @brief Sets the color multiplier applied to the image. \
  * \
  * Accepts both direct RGBA values and theme color tokens via UiColor. \
  * \
  * @param[in] color The color to multiply with the image \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetImageColor(const UiColor& color) { ImageView::SetImageColor(color); return *this; } \
  /** \
  * @brief Sets the pixel area used to display a sub-region of the image. \
  * \
  * The area is specified as normalized coordinates: (x, y, width, height) \
  * where each component is in the range [0, 1]. \
  * \
  * @param[in] pixelArea The normalized sub-region of the image to display \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPixelArea(const Vector4& pixelArea) { ImageView::SetPixelArea(pixelArea); return *this; } \
  /** \
  * @brief Sets whether the view size is fitted to the image's natural aspect ratio. \
  * \
  * When enabled, if one dimension is fixed (via layout params or MATCH_PARENT) and the \
  * other is unconstrained, the unconstrained dimension is automatically computed from \
  * the image's natural aspect ratio after the image has loaded. \
  * \
  * @param[in] enable True to fit the view size to the image \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetFitSizeToImage(bool enable) { ImageView::SetFitSizeToImage(enable); return *this; } \
  /** \
  * @brief Sets the sampling mode used when scaling the image. \
  * \
  * @param[in] samplingMode The sampling mode to use \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSamplingMode(Ui::SamplingMode::Type samplingMode) { ImageView::SetSamplingMode(samplingMode); return *this; } \
  /** \
  * @brief Sets how the image is fitted within the view bounds. \
  * \
  * @param[in] fittingMode The fitting mode to use \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetFittingMode(Ui::FittingMode::Type fittingMode) { ImageView::SetFittingMode(fittingMode); return *this; } \
  /** \
  * @brief Sets the desired image dimensions used as a hint for the image loader. \
  * \
  * @param[in] size The desired width and height in pixels \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetDesiredSize(Ui::ImageDimensions size) { ImageView::SetDesiredSize(size); return *this; } \
  /** \
  * @brief Sets whether the view size is determined synchronously during image loading. \
  * \
  * When enabled, the natural size is resolved synchronously so the layout \
  * does not need a second pass after the image loads. \
  * \
  * @param[in] synchronous True to enable synchronous sizing \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSynchronousSizing(bool synchronous) { ImageView::SetSynchronousSizing(synchronous); return *this; } \
  /** \
  * @brief Sets whether the image uses pre-multiplied alpha. \
  * \
  * @param[in] preMultiplied True if the image has pre-multiplied alpha \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPreMultipliedAlpha(bool preMultiplied) { ImageView::SetPreMultipliedAlpha(preMultiplied); return *this; } \
  /** \
  * @brief Sets the URL of an alpha mask image. \
  * \
  * When set, the alpha channel of the mask image is applied to the main image. \
  * \
  * @param[in] maskUrl The URL of the alpha mask image \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetAlphaMaskUrl(const Dali::String& maskUrl) { ImageView::SetAlphaMaskUrl(maskUrl); return *this; } \
  /** \
  * @brief Sets whether the image should be cropped to the mask bounds. \
  * \
  * @param[in] cropToMask True to crop the image to the mask \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetCropToMask(bool cropToMask) { ImageView::SetCropToMask(cropToMask); return *this; } \
  /** \
  * @brief Sets the masking mode. \
  * \
  * @param[in] maskingMode The masking mode to use \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetMaskingMode(Ui::MaskingType::Type maskingMode) { ImageView::SetMaskingMode(maskingMode); return *this; } \
  /** \
  * @brief Sets the release policy for the image resource. \
  * \
  * Controls when the image texture is released from memory. \
  * \
  * @param[in] releasePolicy The release policy to use \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetReleasePolicy(Ui::ReleasePolicy::Type releasePolicy) { ImageView::SetReleasePolicy(releasePolicy); return *this; } \
  /** \
  * @brief Sets whether the image is loaded synchronously. \
  * \
  * @param[in] synchronous True to load the image on the main thread synchronously \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSynchronousLoading(bool synchronous) { ImageView::SetSynchronousLoading(synchronous); return *this; } \
  /** \
  * @brief Sets whether fast-track uploading is enabled. \
  * \
  * When enabled, the image is uploaded to the GPU on a background thread \
  * to reduce main-thread stalls. \
  * \
  * @param[in] fastTrack True to enable fast-track uploading \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetFastTrackUploading(bool fastTrack) { ImageView::SetFastTrackUploading(fastTrack); return *this; } \
  /** \
  * @brief Sets whether EXIF orientation metadata is applied automatically. \
  * \
  * @param[in] orientationCorrection True to apply orientation correction \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetOrientationCorrection(bool orientationCorrection) { ImageView::SetOrientationCorrection(orientationCorrection); return *this; } \
  /** \
  * @brief Sets the N-patch border insets. \
  * \
  * The border is specified as (left, top, right, bottom) pixel values. \
  * Setting a non-zero border activates N-patch rendering. \
  * \
  * @param[in] border The border insets as (left, top, right, bottom) \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetBorder(const Vector4& border) { ImageView::SetBorder(border); return *this; } \
  /** \
  * @brief Sets whether only the N-patch border regions are rendered. \
  * \
  * When enabled, the center region of the N-patch is not rendered. \
  * \
  * @param[in] borderOnly True to render only the border regions \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetBorderOnly(bool borderOnly) { ImageView::SetBorderOnly(borderOnly); return *this; } \
  /** \
  * @brief Sets the depth index of the image visual. \
  * \
  * The depth index controls the rendering order of visuals within the same \
  * layer. Higher values are rendered on top. \
  * \
  * @param[in] depthIndex The depth index to assign to the image visual \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetDepthIndex(int depthIndex) { ImageView::SetDepthIndex(depthIndex); return *this; }
