// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_LOTTIEANIMATIONVISUAL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VISUALBASE_METHODS(ChildClass) \
  /** \
  * @brief Sets the resource url of the LottieAnimationVisual. \
  * \
  * @param[in] resourceUrl The resource url to set \
  */ \
  ChildClass& SetResourceUrl(const Dali::String& resourceUrl) { LottieAnimationVisual::SetResourceUrl(resourceUrl); return *this; } \
  /** \
  * @brief Sets whether the image is loaded synchronously. \
  * \
  * @param[in] synchronous True to load the image on the main thread synchronously \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSynchronousLoading(bool synchronous) { LottieAnimationVisual::SetSynchronousLoading(synchronous); return *this; } \
  /** \
  * @brief Sets the desired width of the LottieAnimationVisual. \
  * \
  * @param[in] desiredWidth The desired width to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetDesiredWidth(int desiredWidth) { LottieAnimationVisual::SetDesiredWidth(desiredWidth); return *this; } \
  /** \
  * @brief Sets the desired height of the LottieAnimationVisual. \
  * \
  * @param[in] desiredHeight The desired height to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetDesiredHeight(int desiredHeight) { LottieAnimationVisual::SetDesiredHeight(desiredHeight); return *this; } \
  /** \
  * @brief Sets the sampling mode of the LottieAnimationVisual. \
  * \
  * @param[in] samplingMode The sampling mode to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSamplingMode(Image::SamplingMode samplingMode) { LottieAnimationVisual::SetSamplingMode(samplingMode); return *this; } \
  /** \
  * @brief Sets the pixel area of the LottieAnimationVisual. \
  * \
  * @param[in] pixelArea The pixel area to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPixelArea(const Dali::Vector4& pixelArea) { LottieAnimationVisual::SetPixelArea(pixelArea); return *this; } \
  /** \
  * @brief Sets the wrap mode for u coordinate of the LottieAnimationVisual. \
  * \
  * @param[in] wrapModeU The wrap mode for u coordinate to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetWrapModeU(Dali::WrapMode::Type wrapModeU) { LottieAnimationVisual::SetWrapModeU(wrapModeU); return *this; } \
  /** \
  * @brief Sets the wrap mode for v coordinate of the LottieAnimationVisual. \
  * \
  * @param[in] wrapModeV The wrap mode for v coordinate to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetWrapModeV(Dali::WrapMode::Type wrapModeV) { LottieAnimationVisual::SetWrapModeV(wrapModeV); return *this; } \
  /** \
  * @brief Sets whether to enable broken image. \
  * \
  * @param[in] enableBrokenImage True to enable broken image \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetEnableBrokenImage(bool enableBrokenImage) { LottieAnimationVisual::SetEnableBrokenImage(enableBrokenImage); return *this; } \
  /** \
  * @brief Sets the load policy of the LottieAnimationVisual. \
  * \
  * @param[in] loadPolicy The load policy to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetLoadPolicy(Image::LoadPolicy loadPolicy) { LottieAnimationVisual::SetLoadPolicy(loadPolicy); return *this; } \
  /** \
  * @brief Sets the release policy of the LottieAnimationVisual. \
  * \
  * @param[in] releasePolicy The release policy to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetReleasePolicy(Image::ReleasePolicy releasePolicy) { LottieAnimationVisual::SetReleasePolicy(releasePolicy); return *this; } \
  /** \
  * @brief Sets whether to correct the image orientation. \
  * \
  * @param[in] orientationCorrection True to correct the image orientation \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetOrientationCorrection(bool orientationCorrection) { LottieAnimationVisual::SetOrientationCorrection(orientationCorrection); return *this; } \
  /** \
  * @brief Sets whether to use synchronous sizing. \
  * \
  * @param[in] synchronousSizing True to use synchronous sizing \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetSynchronousSizing(bool synchronousSizing) { LottieAnimationVisual::SetSynchronousSizing(synchronousSizing); return *this; } \
  /** \
  * @brief Sets the loop count of the LottieAnimationVisual. \
  * \
  * @param[in] loopCount The loop count to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetLoopCount(int loopCount) { LottieAnimationVisual::SetLoopCount(loopCount); return *this; } \
  /** \
  * @brief Sets the play range of the LottieAnimationVisual. \
  * \
  * @param[in] playRange The play range to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetPlayRange(const Dali::Property::Array& playRange) { LottieAnimationVisual::SetPlayRange(playRange); return *this; } \
  /** \
  * @brief Sets the stop behavior of the LottieAnimationVisual. \
  * \
  * @param[in] stopBehavior The stop behavior to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetStopBehavior(AnimatedImage::StopBehavior stopBehavior) { LottieAnimationVisual::SetStopBehavior(stopBehavior); return *this; } \
  /** \
  * @brief Sets the frame speed factor of the LottieAnimationVisual. \
  * \
  * @param[in] frameSpeedFactor The frame speed factor to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetFrameSpeedFactor(float frameSpeedFactor) { LottieAnimationVisual::SetFrameSpeedFactor(frameSpeedFactor); return *this; } \
  /** \
  * @brief Sets the looping mode of the LottieAnimationVisual. \
  * \
  * @param[in] loopingMode The looping mode to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetLoopingMode(LottieAnimation::LoopingMode loopingMode) { LottieAnimationVisual::SetLoopingMode(loopingMode); return *this; } \
  /** \
  * @brief Sets whether to redraw when the visual is scaled down. \
  * \
  * @param[in] redrawInScalingDown True to redraw when scaled down \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetRedrawInScalingDown(bool redrawInScalingDown) { LottieAnimationVisual::SetRedrawInScalingDown(redrawInScalingDown); return *this; } \
  /** \
  * @brief Sets whether to redraw when the visual is scaled up. \
  * \
  * @param[in] redrawInScalingUp True to redraw when scaled up \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetRedrawInScalingUp(bool redrawInScalingUp) { LottieAnimationVisual::SetRedrawInScalingUp(redrawInScalingUp); return *this; } \
  /** \
  * @brief Sets whether to enable frame cache. \
  * \
  * @param[in] enableFrameCache True to enable frame cache \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetEnableFrameCache(bool enableFrameCache) { LottieAnimationVisual::SetEnableFrameCache(enableFrameCache); return *this; } \
  /** \
  * @brief Sets whether to notify after rasterization. \
  * \
  * @param[in] notifyAfterRasterization True to notify after rasterization \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetNotifyAfterRasterization(bool notifyAfterRasterization) { LottieAnimationVisual::SetNotifyAfterRasterization(notifyAfterRasterization); return *this; } \
  /** \
  * @brief Sets the render scale of the LottieAnimationVisual. \
  * \
  * @param[in] renderScale The render scale to set \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetRenderScale(float renderScale) { LottieAnimationVisual::SetRenderScale(renderScale); return *this; } \
  /** \
  * @brief Sets a per-frame dynamic property callback on a specific layer/element. \
  * \
  * Ownership of DynamicPropertyInfo::callback is transferred to the visual. \
  * \
  * @param[in] info The dynamic property info \
  * @return Reference to this for fluent chaining \
  */ \
  ChildClass& SetDynamicProperty(const LottieAnimation::DynamicPropertyInfo& info) { LottieAnimationVisual::SetDynamicProperty(info); return *this; }
